### ISSUE TITLE
aarch64 test failed on memory.tar

### ISSUE THREAD

**Issue by sixshotx** [gtcasl/qsim#16]
command line:
./tester 1 ../state.1.a64 arm64/memory.tar

qemu output:
bling callback generation for pid 37.
[    7.900271 ] memory[37]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x90000006
[    7.914421 ] pgd = ffffffc0198dc000
[    7.917219 ] [00000000] *pgd=00000000598de003, *pud=00000000598de003, *pmd=0000000000000000
[    7.925618 ]
[    7.928301 ] CPU: 0 PID: 37 Comm: memory Not tainted 4.1.15 #2
[    7.930261 ] Hardware name: linux,dummy-virt (DT)
    [    7.935133 ] task: ffffffc008cbb000 ti: ffffffc0198f0000 task.ti: ffffffc0198f0000
    [    7.939697 ] pc : [<00000000004009f4>] lr : [<00000000004009ec>] pstate: 60000000
    [    7.945314 ] sp : 0000007fc452b690
    [    7.947019 ] x29: 0000007fc452b690 x28: 0000000000000000
    [    7.950862 ] x27: 0000000000000000 x26: 0000000000000000
    [    7.957142 ] x25: 0000000000000000 x24: 00000000004001a0
    [    7.960651 ] x23: 0000000000000000 x22: 00000000004920d8
    [    7.964208 ] x21: 0000000000492020 x20: 0000000000000000
    [    7.968416 ] x19: 00000000004001a0 x18: 0000000000000000
    [    7.974541 ] x17: 000000000055b000 x16: 0000000000560000
    [    7.979257 ] x15: 0000000000560000 x14: 000000000055a758
    [    7.984332 ] x13: ffffff0000000000 x12: 000000000055d5a0
    [    7.988900 ] x11: 0000000000000003 x10: 0101010101010101
    [    7.995098 ] x9 : 0000000000000001 x8 : 000000000000001c
    [    7.997843 ] x7 : 0000007fc452b578 x6 : 000000000055d800
    [    8.003978 ] x5 : 0000000000000003 x4 : 0000000012078620
    [    8.008771 ] x3 : 0000000012078610 x2 : 0000000000000000
    [    8.014221 ] x1 : 0000000012078610 x0 : 00000000aaaaaaaa
    [    8.018137 ]
    Segmentation fault
    --- program exit, will shutdown shortly... ---
    QEMU: Terminated

**Comment by pranith** [comment]
What setup are you using? OS/aarch64 gcc version etc., would be useful. What does the icount test give?

Can you do the following and post the output?

$ make distclean
$ rm -f state.1\* initrd/initrd.cpio*
$ make tests

**Comment by sixshotx** [comment]
Here is my setup:
OS: fedora 21
aarch64 toolchain: gcc-linaro-5.1-2015.08-x86_64_aarch64-linux-gnu

I got the same error after your instructions (is it possible that there is a bug in the prebuild images):

bling callback generation for pid 37.
[    7.869824 ] memory[37]: unhandled level 2 translation fault (11) at 0x00000000, esr 0x90000006
[    7.884519 ] pgd = ffffffc0198dc000
[    7.887359 ] [00000000] *pgd=00000000598de003, *pud=00000000598de003, *pmd=0000000000000000
[    7.892504 ]
[    7.894808 ] CPU: 0 PID: 37 Comm: memory Not tainted 4.1.15 #2
[    7.896822 ] Hardware name: linux,dummy-virt (DT)
    [    7.900445 ] task: ffffffc008ccc000 ti: ffffffc0198f0000 task.ti: ffffffc0198f0000
    [    7.903673 ] pc : [<00000000004009f4>] lr : [<00000000004009ec>] pstate: 60000000
    [    7.905835 ] sp : 0000007fc2988160
    [    7.907500 ] x29: 0000007fc2988160 x28: 0000000000000000
    [    7.911246 ] x27: 0000000000000000 x26: 0000000000000000
    [    7.913879 ] x25: 0000000000000000 x24: 00000000004001a0
    [    7.916539 ] x23: 0000000000000000 x22: 00000000004920d8
    [    7.920824 ] x21: 0000000000492020 x20: 0000000000000000
    [    7.923505 ] x19: 00000000004001a0 x18: 0000000000000000
    [    7.926160 ] x17: 000000000055b000 x16: 0000000000560000
    [    7.929874 ] x15: 0000000000560000 x14: 000000000055a758
    [    7.932604 ] x13: ffffff0000000000 x12: 000000000055d5a0
    [    7.935258 ] x11: 0000000000000003 x10: 0101010101010101
    [    7.941335 ] x9 : 0000000000000001 x8 : 000000000000001c
    [    7.944171 ] x7 : 0000007fc2988048 x6 : 000000000055d800
    [    7.946818 ] x5 : 0000000000000003 x4 : 00000000383d6620
    [    7.950516 ] x3 : 00000000383d6610 x2 : 0000000000000000
    [    7.953990 ] x1 : 00000000383d6610 x0 : 00000000aaaaaaaa
    [    7.957212 ]
    Segmentation fault
    --- program exit, will shutdown shortly... ---

**Comment by pranith** [comment]
The version of gcc you are using is handling asm inputs differently. This should be fixed by 5835f20. Can you please verify that the latest git version works for you?

**Comment by sixshotx** [comment]
The bug is fixed with the assembly modification. Thanks.
