### ISSUE TITLE
qsim->booted not function as previous

### ISSUE THREAD

**Issue by sixshotx** [gtcasl/qsim#21]
manifold used to use booted() to determine whether qsim completes an application as follow:
if(!qsim_osd->booted(core_id)) {
                queue_item.cb_type = Qsim::QueueItem::TERMINATED;
            }

The current version does not update running[i] as before, so an app_end callback is needed in spx to exit the loop.

**Comment by pranith** [comment]
I fixed this in 5962a82. Can you check if it works?
