### ISSUE TITLE
qsim->run() now ignores cpu_id

### ISSUE THREAD

**Issue by sixshotx** [gtcasl/qsim#22]
Just put it up here for discussion The qsim->run(cpu_id, n) will always execute on cpu 0 as there is only one qemu instance for all cores. It is a big impact on the spx frontend to fetch instruction and communicate with qsim though.

**Comment by pranith** [comment]
The run(n) api will run qemu for n instructions. We do not have control over which CPU these instructions will run on. I think using queue interface, we need to buffer the callbacks and wait for callbacks on the desired CPU to be invoked.

**Comment by pranith** [comment]
Fixed in ee5440ce1282
