### ISSUE TITLE
qsim execution results depend on the run() granularity.

### ISSUE THREAD

**Issue by sixshotx** [gtcasl/qsim#32]
Let INST be the number of instructions passed to osd.run(). Take barnes.tar for example in a 4-core configuration. When INST < ~5000, a maximum of 2 cores are assigned to barnes, while when INST > 5000, all the 4 cores are active.

**Comment by pranith** [comment]
This should be fixed with commit f6ed772fd4e3104e31cd26ab016513058dca9230. Can you please verify?

**Comment by sixshotx** [comment]
Initial test seems reasonable using the spx framework. I am now testing it against the manifold using splash-2 benchmark for 500M cycles.

**Comment by sixshotx** [comment]
according to the results of barnes, water-ns and lu-nc, the patch is working.
