### ISSUE TITLE
missing callbacks

### ISSUE THREAD

**Issue by sixshotx** [gtcasl/qsim#33]
using the tester framework, I observed some of the mem_cbs and reg_cbs are missing. Need further investigation.

**Comment by pranith** [comment]
I ran barnes through the tester. I see these numbers:

Inst: 2118763654
Mem : 1360759555
Reg : 1937980037

That seems reasonable, no?

**Comment by sixshotx** [comment]
Numbers are reasonable.

**Comment by pranith** [comment]
Can you test and post your numbers? Are you seeing something similar or is it widely different?

**Comment by sixshotx** [comment]
Here is my result running barnes till the end.

Inst: 2116577296
Mem : 1360738267
Reg : 1933549309

**Comment by sixshotx** [comment]
Please merge the patch, the fix works with manifold.
