### ISSUE TITLE
[suggestion] make a base virtual class for QueueItem

### ISSUE THREAD

**Issue by sixshotx** [gtcasl/qsim#35]
Pranith and I have a discussion on how manifold manipulates the queueItem for spx component. Pranith suggested me to create a NEW queueItem inside the manifold and leave original one in qsim unchanged. Yet the existing implementation of queueItem uses "struct", which is hard to extend/add new members/functions by the wrappers. I have to duplicate the queueItem and add new modifications on top of it, kind of ugly. I think we need to rethink how to implement queueItem in a more effective way, say virtual base class.

**Comment by pranith** [comment]
I think it is not a good idea to duplicate stuff. Can you update the current QueueItem in qsim and send that in a PR? I am open to updating qsim's QueueItem if it saves duplication overhead...
