### ISSUE TITLE
Use record/replay framework in qemu for deterministic execution

### ISSUE THREAD

**Issue by pranith** [gtcasl/qsim#44]
QEMU has a record-replay feature which records the non-deterministic events which affect the program execution. To reliably reproduce an execution, we need to use this feature in qsim.

**Comment by sudhakar7** [comment]
A very useful feature. Can we ensure that there is documentation of this feature  in the Qsim documentation?

# 

Sudhakar Yalamanchili

**Comment by pranith** [comment]
yes, I will add this to the documentation once it is implemented.
