### ISSUE TITLE
pids not reported in interactive mode

### ISSUE THREAD

**Issue by ndesh26** [gtcasl/qsim#81]
When running an application in interactive mode, the get_tid function always returns 0. This is due to the use of unmodified kernel in the x86_64 image.

**Comment by garg-saurav** [comment]
Hey @ndesh26 I am facing the same issue. Did you find any workaround?

**Comment by ndesh26** [comment]
My memory's hazy, but I think it was related to a custom patch not getting applied. `qsim` was using a image without the required patches. I am referring to `linux/linux-4.1.qsim.patch` in the source tree.

**Comment by garg-saurav** [comment]
I saw that patch but when I tried to use the bzImage generated by [getkernel.sh](https://github.com/gtcasl/qsim/blob/master/linux/getkernel.sh) (it applies the patch and then builds the kernel), qsim didn't give any output. I was wondering if there is something else I am missing.

**Comment by garg-saurav** [comment]
Specifically, I replaced the [kernel_path](https://github.com/gtcasl/qsim/blob/b1e33516426663f277a5da5b56b2b59d28fa5099/qsim.cpp#L245) with path to bzImage

**Comment by ndesh26** [comment]
I don't remember the exact details now. I think I also tried using Linux version 2.6.34 and It was running properly with that image. Please try it with that version once.
