### ISSUE TITLE
Simulation hangs on "make tests"

### ISSUE THREAD

**Issue by dayeol** [gtcasl/qsim#85]
The newest version (v2.6) of QSim irregularly hangs on the middle of "make tests".
I'm using Amazon EC2's c3.2xlarge instance with Ubuntu-14.04 LTS AMI.

When I run "./sudo_setup.sh", the script hangs at the line "make tests"
after stdout "Copying benchmark binary...".

I debugged it a little, and found that it hangs after the last magic callback with "0xc75c0020", which indicates the context switch (?).

Could you let me know what was wrong?

**Comment by pranith** [comment]
Can you please report what GCC version you are using? There was a problem with 4.8 from what I remember.

**Comment by dayeol** [comment]
Thanks for your quick reply!
gcc --version gives this:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Why gcc version matters? Can I fix this without changing gcc version?

**Comment by pranith** [comment]
We use C++11 in the library and 4.8 had some problems. We did not dig the issue further. Can you try installing 4.9 and check? It should be really easy on Ubuntu.

**Comment by dayeol** [comment]
GCC 4.9 doesn't work either.
