### ISSUE TITLE
Add support for Ubuntu 18.04

### ISSUE THREAD

**Issue by pranith** [gtcasl/qsim#89]
Build currently fails.

**Comment by TheNetAdmin** [comment]
I successfully built the project on 18.04, and the ARM mode can run.

BUT x86 mode is not able to run, don't know why.

**Comment by vishalgupta97** [comment]
I am also not able to build for x86. Its stuck in fast-forwarding. Is it related to Ubuntu version ? Was it working in previous Ubuntu Version ?

**Comment by pranith** [comment]
@vishalgupta97 what are you trying to do? The project is not currently being maintained, but I would like to understand the problem and any patches are welcome.

**Comment by vishalgupta97** [comment]
I ran the script setup-sudo.sh, it run until make tests and is stuck there. It is able to complete ARM tests, but when it comes to x86, its stuck in fast-forwarding for like 130 hours. After that I killed it. 

I am trying to setup qsim for my work and generates traces of binaries.
Was QSim for x86 working on Ubuntu 16.04 ?

**Comment by vishalgupta97** [comment]
Following the configuration present in Travis CI, I was able to run QSim for x86 with Ubuntu 14.04
